package com.palcraft;

import java.util.List;
import java.util.Map;

/** GENERATED by tools/gen.py from sheets/*.json. Do not edit; change the sheets. */
public final class GeneratedSheets {
    private GeneratedSheets() {}

    public static final List<PalDef> PALS = List.of(
        new PalDef("lamball", "Lamball", 14f, 2f, 0.22, 0.6f, 0.7f, 1.0f, 0.0f, false, "none", 0, 15658734, 16757960, 15658734, 16757960),
        new PalDef("cattiva", "Cattiva", 12f, 3f, 0.28, 0.55f, 0.65f, 0.95f, 0.1f, false, "none", 0, 15111750, 16764006, 15111750, 16764006),
        new PalDef("foxparks", "Foxparks", 14f, 4f, 0.3, 0.6f, 0.7f, 1.0f, 0.3f, true, "ignite", 3, 13785664, 16766720, 13785664, 16766720),
        new PalDef("pengullet", "Pengullet", 16f, 3f, 0.25, 0.55f, 0.8f, 1.0f, 0.3f, false, "minecraft:slowness", 3, 3958984, 16777215, 3958984, 16777215)
    );

    public static final Map<String, PalDef> PAL_BY_ID = Map.ofEntries(
        Map.entry("lamball", PALS.get(0)),
        Map.entry("cattiva", PALS.get(1)),
        Map.entry("foxparks", PALS.get(2)),
        Map.entry("pengullet", PALS.get(3))
    );

    public static final List<SpawnRow> SPAWNS = List.of(
        new SpawnRow("lamball", "minecraft", "plains", 10, 2, 4),
        new SpawnRow("lamball", "minecraft", "sunflower_plains", 10, 2, 4),
        new SpawnRow("lamball", "minecraft", "meadow", 8, 2, 3),
        new SpawnRow("cattiva", "minecraft", "forest", 8, 1, 3),
        new SpawnRow("cattiva", "minecraft", "birch_forest", 8, 1, 3),
        new SpawnRow("cattiva", "minecraft", "taiga", 6, 1, 2),
        new SpawnRow("foxparks", "minecraft", "savanna", 8, 1, 2),
        new SpawnRow("foxparks", "minecraft", "desert", 6, 1, 2),
        new SpawnRow("foxparks", "minecraft", "badlands", 6, 1, 2),
        new SpawnRow("pengullet", "minecraft", "snowy_plains", 8, 2, 3),
        new SpawnRow("pengullet", "minecraft", "snowy_taiga", 6, 1, 3),
        new SpawnRow("pengullet", "minecraft", "ice_spikes", 6, 1, 3)
    );

    public static final int SPHERE_MAX_STACK = 16;
    public static final double SPHERE_BASE_CATCH = 0.5;
    public static final float SPHERE_THROW_SPEED = 1.5f;
}
